### ISSUE TITLE
turn on autoescape in Jinja2

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python-plugins#9]
Jinja2 sez autoescape is bad, but I disagree. See https://github.com/gratipay/gratipay.com/issues/722 for discussion.

**Comment by pjz** [comment]
I'd rather leave it the default, but document how to turn it on if you want it.  Could/should also serve to document how, in general, to tweak renderers.

**Comment by whit537** [comment]
The difference in our case is that we're almost exclusively HTML/XML in context. Jinja2 might be used for email, but aspen-jinja2 is almost certainly being used for HTML.

**Comment by Changaco** [comment]
aspen-jinja2 should be able to determine what it's being used for (via the Content-Type) and thus whether or not it's appropriate to turn on the autoescape.

**Comment by Changaco** [comment]
I have a branch ready for this, waiting for the next Aspen release.
